/**
 * 10 taunt lines per animal — personalized with name/emoji.
 * Pick with getRandomTaunt(animalIndex).
 */
const TAUNT_BUILDERS = [
  (a) => `${a.emoji} Is that your best shot? The ${a.name} laughs!`,
  (a) => `${a.emoji} Oof… just kidding. Barely felt it!`,
  (a) => `${a.emoji} Come closer, peacekeeper. The ${a.name} wants a rematch!`,
  (a) => `${a.emoji} You punch like a tourist. This ${a.name} lives here!`,
  (a) => `${a.emoji} Ha! The ${a.name} has seen scarier snacks!`,
  (a) => `${a.emoji} Keep swinging — the ${a.name} is just warming up!`,
  (a) => `${a.emoji} That tickled. Got anything ${a.name}-sized?`,
  (a) => `${a.emoji} Nice effort! Still not scaring this ${a.name}!`,
  (a) => `${a.emoji} The ${a.name} yawns… try again!`,
  (a) => `${a.emoji} Peace? Never heard of it. Bring it on!`,
  (a) => `${a.emoji} Your aura is weak. The ${a.name} is chaos!`,
  (a) => `${a.emoji} Strike harder! This ${a.name} has places to nap!`,
  (a) => `${a.emoji} Was that an attack or a friendly wave?`,
  (a) => `${a.emoji} The zoo's loudest ${a.name} says: miss me!`,
  (a) => `${a.emoji} Soft human energy detected. Rejected!`,
  (a) => `${a.emoji} One Step Closer to… getting dunked by a ${a.name}!`,
  (a) => `${a.emoji} Cute punch. The ${a.name} rates it 2/10.`,
  (a) => `${a.emoji} You woke the ${a.name}. Bad idea.`,
  (a) => `${a.emoji} My grandma ${a.name} hits harder than that!`,
  (a) => `${a.emoji} Pathetic! The ${a.name} demands a real fight!`,
];

const ANIMAL_TAUNT_FLAVOR = {
  Whale: [
    '🐋 Blub blub — your punches float away!',
    '🐋 I\'m bigger than your whole strategy!',
    '🐋 Splash zone incoming. You\'re soaked!',
    '🐋 Deep-sea disrespect activated!',
    '🐋 You can\'t pacify this much whale!',
    '🐋 Ocean\'s favorite bully says hi!',
    '🐋 That hit bounced off my blowhole!',
    '🐋 Call me Captain Chaos!',
    '🐋 Your XP looks like plankton to me!',
    '🐋 Breach! Crush! Taunt!',
  ],
  Elephant: [
    '🐘 Never forget… how weak that punch was!',
    '🐘 Trunk slap incoming!',
    '🐘 I step on problems. You are a problem!',
    '🐘 Peanuts? No. Pain? Yes!',
    '🐘 My ears hear your fear!',
    '🐘 Stampede of sass!',
    '🐘 That barely wrinkled my hide!',
    '🐘 Big animal. Bigger attitude!',
    '🐘 Try again, tiny human!',
    '🐘 Peace is canceled. Chaos is booked!',
  ],
  Lion: [
    '🦁 Hear me roar… over your weak attack!',
    '🦁 King of the zoo. Jester of your aim!',
    '🦁 Mane event: you lose!',
    '🦁 Dinner reservations: YOU!',
    '🦁 Cub energy detected. Pathetic!',
    '🦁 The pride is laughing!',
    '🦁 Claws out. Confidence higher!',
    '🦁 That was cute. Now watch THIS!',
    '🦁 Royal smackdown incoming!',
    '🦁 Bow down or bounce!',
  ],
  Tiger: [
    '🐯 Stripe-certified smack talk!',
    '🐯 Pounce first, ask peace later!',
    '🐯 Your attack has no stripes!',
    '🐯 Orange you glad I\'m fierce?',
    '🐯 Soft human. Sharp tiger!',
    '🐯 Ambush mode: enabled!',
    '🐯 That tickled my whiskers!',
    '🐯 Jungle justice says miss!',
    '🐯 Roar so loud your XP shakes!',
    '🐯 Catitude overload!',
  ],
  Ant: [
    '🐜 Tiny but terrifying!',
    '🐜 Army of attitude!',
    '🐜 You missed… by six legs!',
    '🐜 Strength in numbers AND sass!',
    '🐜 Picnic\'s over. Pain\'s on!',
    '🐜 Lift your game — I lift crumbs AND chaos!',
    '🐜 Formic acid? Formic ATTITUDE!',
    '🐜 Colony says you\'re toast!',
    '🐜 Small package. Huge roast!',
    '🐜 Mandibles loaded. Ego ready!',
  ],
  Microbe: [
    '🦠 Too small to see. Too big to ignore!',
    '🦠 Infection of attitude!',
    '🦠 You can\'t punch what you can\'t find!',
    '🦠 Microscope required. Courage optional!',
    '🦠 Split and multiply… your problems!',
    '🦠 Final boss energy in a droplet!',
    '🦠 Immune to your vibes!',
    '🦠 Peace? I\'m pure chaos DNA!',
    '🦠 Contagiously rude!',
    '🦠 One cell. Infinite shade!',
  ],
  Mosquito: [
    '🦟 Bzzzt! Missed me!',
    '🦟 Free blood samples? Asking for a friend!',
    '🦟 Itchy yet?',
    '🦟 Night\'s most annoying MVP!',
    '🦟 Slap air all you want!',
    '🦟 Dinner is served… and it\'s you!',
    '🦟 Wings of chaos!',
    '🦟 Tiny vampire energy!',
    '🦟 Your DEF means nothing to me!',
    '🦟 Bzzz-bye, soft human!',
  ],
  Shark: [
    '🦈 Chomp first, taunt forever!',
    '🦈 That punch floated. I don\'t!',
    '🦈 Blood in the water… of your confidence!',
    '🦈 Fins up. Hope down!',
    '🦈 Jaws: 1. Peace: 0.',
    '🦈 Circling… your mistakes!',
    '🦈 Apex attitude!',
    '🦈 Swim away while you can!',
    '🦈 Bite-sized human detected!',
    '🦈 Dorsal of disrespect!',
  ],
  Snake: [
    '🐍 Ssssuch a weak strike!',
    '🐍 Coil. Strike. Roast.',
    '🐍 Venom? Optional. Sass? Mandatory!',
    '🐍 You hiss-took my power!',
    '🐍 Slither around your defense!',
    '🐍 Cold blood. Hot takes!',
    '🐍 Rattle your resolve!',
    '🐍 Forked tongue, forked fate!',
    '🐍 Squeeze the peace out of you!',
    '🐍 Sssurrender already!',
  ],
  Owl: [
    '🦉 Who? Who thought that would work?',
    '🦉 Night vision sees your bad aim!',
    '🦉 Wise enough to dodge THAT!',
    '🦉 Hoo-less attack!',
    '🦉 Silent wings. Loud roast!',
    '🦉 Knowledge is knowing you missed!',
    '🦉 Twit-twoo… twit-TOO BAD!',
    '🦉 Head spin of shame — yours!',
    '🦉 Soft human. Sharp beak energy!',
    '🦉 The forest is laughing!',
  ],
  Penguin: [
    '🐧 Slide into your DMs: Defeat!',
    '🐧 Formal wear. Informal violence!',
    '🐧 Waddle of war!',
    '🐧 Ice cold comeback!',
    '🐧 Flap flap… flop for you!',
    '🐧 Antarctic attitude!',
    '🐧 That punch slipped!',
    '🐧 Tuxedoed trouble!',
    '🐧 Fish for breakfast. You for lunch!',
    '🐧 Happy feet, unhappy human!',
  ],
  Frog: [
    '🐸 Ribbit… of disrespect!',
    '🐸 Hop over your attack!',
    '🐸 Sticky tongue. Stickier shade!',
    '🐸 Pond boss online!',
    '🐸 Leap of chaos!',
    '🐸 Your aim is toad-ally bad!',
    '🐸 Slimy wins!',
    '🐸 Croak now, cry later!',
    '🐸 Fly catcher. Punch catcher!',
    '🐸 Amphibian arrogance!',
  ],
  Butterfly: [
    '🦋 Pretty? Yes. Harmless? Nope!',
    '🦋 Flutter away from that miss!',
    '🦋 Winged wrath!',
    '🦋 Beauty AND the roast!',
    '🦋 Metamorphosis into mayhem!',
    '🦋 Soft wings. Sharp words!',
    '🦋 Pollinate your panic!',
    '🦋 That attack was basic!',
    '🦋 Cocoon of confidence!',
    '🦋 Butterfly effect: you lose!',
  ],
  Scorpion: [
    '🦂 Stinger loaded. Patience empty!',
    '🦂 Tail first. Feelings later!',
    '🦂 Desert\'s favorite villain!',
    '🦂 Pinch of panic!',
    '🦂 Armor thick. Compassion thin!',
    '🦂 One jab away from legend!',
    '🦂 Crawl into your nightmares!',
    '🦂 That tickled my claws!',
    '🦂 Venomous vibes only!',
    '🦂 Sideways walk. Forward chaos!',
  ],
  Spider: [
    '🕷 Caught in my web of shade!',
    '🕷 Eight legs. Zero mercy!',
    '🕷 Silk soft. Roast hard!',
    '🕷 Creepy-crawly comeback!',
    '🕷 Your attack got stuck!',
    '🕷 Spinnerets of sass!',
    '🕷 Dinner\'s on the web… it\'s you!',
    '🕷 Jump scare punchline!',
    '🕷 Arachnid attitude!',
    '🕷 Weave. Wait. Win!',
  ],
  Honeybee: [
    '🐝 Not the bees—wait, YES the bees!',
    '🐝 Buzz off… after this roast!',
    '🐝 Hive mind says you missed!',
    '🐝 Sweet honey. Sour defeat!',
    '🐝 Stinger protocol engaged!',
    '🐝 Pollen AND problems!',
    '🐝 Worker bee. Chaos CEO!',
    '🐝 That punch was un-bee-lievably weak!',
    '🐝 Swarm energy!',
    '🐝 Bzzzt! Critical sass!',
  ],
  'T-Rex': [
    '🦖 Tiny arms. Massive shade!',
    '🦖 Chomp chomp, soft human!',
    '🦖 Cretaceous comeback!',
    '🦖 Extinct? Never. Your hope? Maybe!',
    '🦖 Roar so loud the map shakes!',
    '🦖 That punch was prehistoricly weak!',
    '🦖 Apex of attitude!',
    '🦖 Short arms. Long roast!',
    '🦖 Fossil fuel for chaos!',
    '🦖 Dino don\'t care!',
  ],
};

function getAnimalTaunts(animalIndex) {
  const animal = ANIMALS[animalIndex];
  if (!animal) return ['…silence. Spooky.'];

  const flavored = ANIMAL_TAUNT_FLAVOR[animal.name];
  if (flavored && flavored.length >= 10) {
    return flavored.slice(0, 10);
  }

  // Deterministic pick of 10 builders so each animal has a stable unique set
  const taunts = [];
  const start = animalIndex % TAUNT_BUILDERS.length;
  for (let i = 0; i < 10; i++) {
    const builder = TAUNT_BUILDERS[(start + i * 3) % TAUNT_BUILDERS.length];
    taunts.push(builder(animal));
  }
  return taunts;
}

function getRandomTaunt(animalIndex) {
  const taunts = getAnimalTaunts(animalIndex);
  return taunts[Math.floor(Math.random() * taunts.length)];
}
